packages:
  - name: redata_reports
    functions:
      - name: run
        runtime: 'python:default'
        web: true
        limits:
          timeout: 420000
          memory: 512
        environment:
          API_FIGSHARE_URL_BASE: ${api_figshare_url_base}
          API_FIGSHARE_TOKEN: ${api_figshare_token}
          GSHEETS_DASHBOARD_POST_URL: ${gsheets_dashboard_post_url}
          GSHEETS_DASHBOARD_KEY: ${gsheets_dashboard_key}
          TOKEN: ${do_token}