on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TrueBrain/actions-flake8@v2 #uses the config in .flake8
        with:
          path: packages
